#!/bin/bash
echo "🔍 Security Tools Usage Examples"
echo "================================"
echo ""
echo "1. Basic NMAP scan:"
echo "   nmap -sV 127.0.0.1"
echo ""
echo "2. Nikto web scan:"
echo "   nikto -h http://localhost:8080"
echo ""
echo "3. SSL analysis with testssl.sh:"
echo "   testssl.sh example.com"
echo ""
echo "4. Nuclei vulnerability scan:"
echo "   nuclei -u http://example.com"
echo ""
echo "5. Directory brute force with dirb:"
echo "   dirb http://example.com"
echo ""
echo "6. Web technology detection with whatweb:"
echo "   whatweb example.com"
echo ""
echo "All tools are now ready to use!"
