"""Refine models

Revision ID: 2d21bea5af12
Revises: ff0b88b62b0a
Create Date: 2025-11-03 14:55:09.192205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d21bea5af12'
down_revision = 'ff0b88b62b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'])

    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('scan_job_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'FIXED', 'RISK_ACCEPTED', 'FALSE_POSITIVE', name='vulnstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'FIXED', 'RISK_ACCEPTED', 'FALSE_POSITIVE', name='vulnstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('scan_job_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('asset_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###
