"""add s scan_type to Scanob

Revision ID: 3a0b921f196b
Revises: 7a9b3d7717ae
Create Date: 2025-11-06 16:24:06.449759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a0b921f196b'
down_revision = '7a9b3d7717ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_type', sa.Enum('network_scan', 'service_enumeration', 'vulnerability_assessment', 'credential_testing', 'web_scan', 'ssl_analysis', 'combined', name='scantype'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index('idx_scan_jobs_scan_type', ['scan_type'], unique=False)
        batch_op.drop_column('insights')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_scan_jobs_scan_type')
        batch_op.drop_column('config')
        batch_op.drop_column('results')
        batch_op.drop_column('error_message')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('scan_type')

    # ### end Alembic commands ###
