"""Add progress field to ScanJob

Revision ID: 464c40a1a6ec
Revises: 507f88b7e7f1
Create Date: 2025-09-26 17:43:16.295240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464c40a1a6ec'
down_revision = '507f88b7e7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
