"""Add logs,index to ScanJob model

Revision ID: 9a8ce2c0d664
Revises: dc3e978a34e6
Create Date: 2025-10-29 12:37:20.413172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8ce2c0d664'
down_revision = 'dc3e978a34e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log', sa.Text(), nullable=True))
        batch_op.create_index('idx_scan_jobs_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_jobs_status_created')
        batch_op.drop_column('log')

    # ### end Alembic commands ###
