"""Add WebScanResult model

Revision ID: dc3e978a34e6
Revises: 338f4fe09c3c
Create Date: 2025-10-29 12:11:14.760094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3e978a34e6'
down_revision = '338f4fe09c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_scan_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'scan_jobs', ['parent_scan_id'], ['id'])

    with op.batch_alter_table('web_scan_results', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_scan_results', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_scan_id')

    # ### end Alembic commands ###
