"""Add error column to scanjob

Revision ID: ff0b88b62b0a
Revises: 12fc57e3ed19
Create Date: 2025-11-03 13:16:58.673900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0b88b62b0a'
down_revision = '12fc57e3ed19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_column('error')

    # ### end Alembic commands ###
